require "machete-dsl/version"
require "machete-dsl/core_ext/hash"
require "machete-dsl/core_ext/string"
require "machete-dsl/core_ext/nil"
require "machete-dsl/core_ext/fixnum"
require "machete-dsl/core_ext/array"
require "machete-dsl/builder"
